#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABPI_HairLayer

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABPI_HairLayer.ABPI_HairLayer_C
// 0x0000 (0x0000 - 0x0000)
class IABPI_HairLayer_C final
{
public:
	void HairPhysLayer(const struct FPoseLink& InPhysPose, struct FPoseLink* HairPhysLayer_0);
	void HairAdjustLayer(const struct FPoseLink& InMeshPose, struct FPoseLink* HairAdjustLayer_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABPI_HairLayer_C">();
	}
	static class IABPI_HairLayer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IABPI_HairLayer_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IABPI_HairLayer_C) == 0x000001, "Wrong alignment on IABPI_HairLayer_C");
static_assert(sizeof(IABPI_HairLayer_C) == 0x000001, "Wrong size on IABPI_HairLayer_C");

}

