#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABPI_CosLayer

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABPI_CosLayer.ABPI_CosLayer_C
// 0x0000 (0x0000 - 0x0000)
class IABPI_CosLayer_C final
{
public:
	void CostumePhysLayer(const struct FPoseLink& InPhysicsPose, struct FPoseLink* CostumePhysLayer_0);
	void CustomAdditiveLayer(const struct FPoseLink& InPose, struct FPoseLink* CustomAdditiveLayer_0);
	void CostumeAdjustLayer(const struct FPoseLink& InMeshPose, struct FPoseLink* CostumeAdjustLayer_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABPI_CosLayer_C">();
	}
	static class IABPI_CosLayer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IABPI_CosLayer_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IABPI_CosLayer_C) == 0x000001, "Wrong alignment on IABPI_CosLayer_C");
static_assert(sizeof(IABPI_CosLayer_C) == 0x000001, "Wrong size on IABPI_CosLayer_C");

}

