#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALS_Controller_BPI

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ALS_Controller_BPI.ALS_Controller_BPI_C
// 0x0000 (0x0000 - 0x0000)
class IALS_Controller_BPI_C final
{
public:
	void BPI_Get_DebugInfo(class ACharacter** DebugFocusCharacter, bool* DebugView, bool* ShowHUD, bool* ShowTraces, bool* ShowDebugShapes, bool* ShowLayerColors, bool* Slomo, bool* ShowCharacterInfo);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ALS_Controller_BPI_C">();
	}
	static class IALS_Controller_BPI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IALS_Controller_BPI_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IALS_Controller_BPI_C) == 0x000001, "Wrong alignment on IALS_Controller_BPI_C");
static_assert(sizeof(IALS_Controller_BPI_C) == 0x000001, "Wrong size on IALS_Controller_BPI_C");

}

