#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALS_Animation_BPI

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "GroundedEntryState_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass ALS_Animation_BPI.ALS_Animation_BPI_C
// 0x0000 (0x0000 - 0x0000)
class IALS_Animation_BPI_C final
{
public:
	void BPI_Jumped();
	void BPI_SetGroundedEntryState(EGroundedEntryState GroundedEntryState);
	void BPI_SetOverlayOverrideState(int32 OverlayOverrideState);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ALS_Animation_BPI_C">();
	}
	static class IALS_Animation_BPI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IALS_Animation_BPI_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IALS_Animation_BPI_C) == 0x000001, "Wrong alignment on IALS_Animation_BPI_C");
static_assert(sizeof(IALS_Animation_BPI_C) == 0x000001, "Wrong size on IALS_Animation_BPI_C");

}

