#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BtlGuiIconComponent

#include "Basic.hpp"

#include "xrd777_structs.hpp"
#include "xrd777_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BtlGuiIconComponent.BP_BtlGuiIconComponent_C
// 0x0030 (0x0130 - 0x0100)
class UBP_BtlGuiIconComponent_C final : public UBtlGuiIconComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0100(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         tempHP;                                            // 0x0108(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         tempSP;                                            // 0x010C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABtlActor*                              tempTarget;                                        // 0x0110(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         tempDamage;                                        // 0x0118(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         tempDamageSP;                                      // 0x011C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBtlGuiIconHit                                tempHit;                                           // 0x0120(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBtlGuiIconDamageType                         tempDamageType;                                    // 0x0121(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          tempIsPotionDamage;                                // 0x0122(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          tempIsBadStatus;                                   // 0x0123(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          tempIsBadStatusRecovery;                           // 0x0124(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          tempIsEndure;                                      // 0x0125(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_126[0x2];                                      // 0x0126(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         tempStepEndureRadio;                               // 0x0128(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_BtlGuiIconComponent(int32 EntryPoint);
	void CreateDamagePanelDelay();
	void ClearSkillNamePanelForBP();
	void CreateTotalDamagePanelForBP(int32 Damage);
	void ClearDamagePanelForBP();
	void StartEncountEffectForBP(bool IsPlayerAdvantage, float Time);
	void Start1MoreEffectForBP(bool IsEnemy, float Time);
	void CreateSkillNamePanelForBP(EBtlCommandType Cmd, int32 ID, bool IsEnemy, float Time);
	void CancelJyokyoHelpForBP();
	void RequestJyokyoHelpForBP(int32 genus, int32 ID, int32 msgNo, int32 var1, int32 var2, float renderTime, float DelayTime, bool forceOverride, int32 flags);
	void CreateDamagePanelForBP(const struct FBtlGuiIconDamage& Data);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BtlGuiIconComponent_C">();
	}
	static class UBP_BtlGuiIconComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BtlGuiIconComponent_C>();
	}
};
static_assert(alignof(UBP_BtlGuiIconComponent_C) == 0x000008, "Wrong alignment on UBP_BtlGuiIconComponent_C");
static_assert(sizeof(UBP_BtlGuiIconComponent_C) == 0x000130, "Wrong size on UBP_BtlGuiIconComponent_C");
static_assert(offsetof(UBP_BtlGuiIconComponent_C, UberGraphFrame) == 0x000100, "Member 'UBP_BtlGuiIconComponent_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_BtlGuiIconComponent_C, tempHP) == 0x000108, "Member 'UBP_BtlGuiIconComponent_C::tempHP' has a wrong offset!");
static_assert(offsetof(UBP_BtlGuiIconComponent_C, tempSP) == 0x00010C, "Member 'UBP_BtlGuiIconComponent_C::tempSP' has a wrong offset!");
static_assert(offsetof(UBP_BtlGuiIconComponent_C, tempTarget) == 0x000110, "Member 'UBP_BtlGuiIconComponent_C::tempTarget' has a wrong offset!");
static_assert(offsetof(UBP_BtlGuiIconComponent_C, tempDamage) == 0x000118, "Member 'UBP_BtlGuiIconComponent_C::tempDamage' has a wrong offset!");
static_assert(offsetof(UBP_BtlGuiIconComponent_C, tempDamageSP) == 0x00011C, "Member 'UBP_BtlGuiIconComponent_C::tempDamageSP' has a wrong offset!");
static_assert(offsetof(UBP_BtlGuiIconComponent_C, tempHit) == 0x000120, "Member 'UBP_BtlGuiIconComponent_C::tempHit' has a wrong offset!");
static_assert(offsetof(UBP_BtlGuiIconComponent_C, tempDamageType) == 0x000121, "Member 'UBP_BtlGuiIconComponent_C::tempDamageType' has a wrong offset!");
static_assert(offsetof(UBP_BtlGuiIconComponent_C, tempIsPotionDamage) == 0x000122, "Member 'UBP_BtlGuiIconComponent_C::tempIsPotionDamage' has a wrong offset!");
static_assert(offsetof(UBP_BtlGuiIconComponent_C, tempIsBadStatus) == 0x000123, "Member 'UBP_BtlGuiIconComponent_C::tempIsBadStatus' has a wrong offset!");
static_assert(offsetof(UBP_BtlGuiIconComponent_C, tempIsBadStatusRecovery) == 0x000124, "Member 'UBP_BtlGuiIconComponent_C::tempIsBadStatusRecovery' has a wrong offset!");
static_assert(offsetof(UBP_BtlGuiIconComponent_C, tempIsEndure) == 0x000125, "Member 'UBP_BtlGuiIconComponent_C::tempIsEndure' has a wrong offset!");
static_assert(offsetof(UBP_BtlGuiIconComponent_C, tempStepEndureRadio) == 0x000128, "Member 'UBP_BtlGuiIconComponent_C::tempStepEndureRadio' has a wrong offset!");

}

