#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BtlGuiIconComponent

#include "Basic.hpp"

#include "BP_BtlGuiIconComponent_classes.hpp"
#include "BP_BtlGuiIconComponent_parameters.hpp"


namespace SDK
{

// Function BP_BtlGuiIconComponent.BP_BtlGuiIconComponent_C.ExecuteUbergraph_BP_BtlGuiIconComponent
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BtlGuiIconComponent_C::ExecuteUbergraph_BP_BtlGuiIconComponent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiIconComponent_C", "ExecuteUbergraph_BP_BtlGuiIconComponent");

	Params::BP_BtlGuiIconComponent_C_ExecuteUbergraph_BP_BtlGuiIconComponent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlGuiIconComponent.BP_BtlGuiIconComponent_C.CreateDamagePanelDelay
// (BlueprintCallable, BlueprintEvent)

void UBP_BtlGuiIconComponent_C::CreateDamagePanelDelay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiIconComponent_C", "CreateDamagePanelDelay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlGuiIconComponent.BP_BtlGuiIconComponent_C.ClearSkillNamePanelForBP
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_BtlGuiIconComponent_C::ClearSkillNamePanelForBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiIconComponent_C", "ClearSkillNamePanelForBP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlGuiIconComponent.BP_BtlGuiIconComponent_C.CreateTotalDamagePanelForBP
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BtlGuiIconComponent_C::CreateTotalDamagePanelForBP(int32 Damage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiIconComponent_C", "CreateTotalDamagePanelForBP");

	Params::BP_BtlGuiIconComponent_C_CreateTotalDamagePanelForBP Parms{};

	Parms.Damage = Damage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlGuiIconComponent.BP_BtlGuiIconComponent_C.ClearDamagePanelForBP
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_BtlGuiIconComponent_C::ClearDamagePanelForBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiIconComponent_C", "ClearDamagePanelForBP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlGuiIconComponent.BP_BtlGuiIconComponent_C.StartEncountEffectForBP
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlayerAdvantage                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BtlGuiIconComponent_C::StartEncountEffectForBP(bool IsPlayerAdvantage, float Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiIconComponent_C", "StartEncountEffectForBP");

	Params::BP_BtlGuiIconComponent_C_StartEncountEffectForBP Parms{};

	Parms.IsPlayerAdvantage = IsPlayerAdvantage;
	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlGuiIconComponent.BP_BtlGuiIconComponent_C.Start1MoreEffectForBP
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsEnemy                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BtlGuiIconComponent_C::Start1MoreEffectForBP(bool IsEnemy, float Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiIconComponent_C", "Start1MoreEffectForBP");

	Params::BP_BtlGuiIconComponent_C_Start1MoreEffectForBP Parms{};

	Parms.IsEnemy = IsEnemy;
	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlGuiIconComponent.BP_BtlGuiIconComponent_C.CreateSkillNamePanelForBP
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EBtlCommandType                         Cmd                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ID                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsEnemy                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BtlGuiIconComponent_C::CreateSkillNamePanelForBP(EBtlCommandType Cmd, int32 ID, bool IsEnemy, float Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiIconComponent_C", "CreateSkillNamePanelForBP");

	Params::BP_BtlGuiIconComponent_C_CreateSkillNamePanelForBP Parms{};

	Parms.Cmd = Cmd;
	Parms.ID = ID;
	Parms.IsEnemy = IsEnemy;
	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlGuiIconComponent.BP_BtlGuiIconComponent_C.CancelJyokyoHelpForBP
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_BtlGuiIconComponent_C::CancelJyokyoHelpForBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiIconComponent_C", "CancelJyokyoHelpForBP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlGuiIconComponent.BP_BtlGuiIconComponent_C.RequestJyokyoHelpForBP
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   genus                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ID                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   msgNo                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   var1                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   var2                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   renderTime                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   DelayTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    forceOverride                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   flags                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BtlGuiIconComponent_C::RequestJyokyoHelpForBP(int32 genus, int32 ID, int32 msgNo, int32 var1, int32 var2, float renderTime, float DelayTime, bool forceOverride, int32 flags)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiIconComponent_C", "RequestJyokyoHelpForBP");

	Params::BP_BtlGuiIconComponent_C_RequestJyokyoHelpForBP Parms{};

	Parms.genus = genus;
	Parms.ID = ID;
	Parms.msgNo = msgNo;
	Parms.var1 = var1;
	Parms.var2 = var2;
	Parms.renderTime = renderTime;
	Parms.DelayTime = DelayTime;
	Parms.forceOverride = forceOverride;
	Parms.flags = flags;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlGuiIconComponent.BP_BtlGuiIconComponent_C.CreateDamagePanelForBP
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FBtlGuiIconDamage&         Data                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UBP_BtlGuiIconComponent_C::CreateDamagePanelForBP(const struct FBtlGuiIconDamage& Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiIconComponent_C", "CreateDamagePanelForBP");

	Params::BP_BtlGuiIconComponent_C_CreateDamagePanelForBP Parms{};

	Parms.Data = std::move(Data);

	UObject::ProcessEvent(Func, &Parms);
}

}

