#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BtlGuiJyokyoHelp

#include "Basic.hpp"

#include "BP_BtlGuiJyokyoHelp_classes.hpp"
#include "BP_BtlGuiJyokyoHelp_parameters.hpp"


namespace SDK
{

// Function BP_BtlGuiJyokyoHelp.BP_BtlGuiJyokyoHelp_C.ExecuteUbergraph_BP_BtlGuiJyokyoHelp
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BtlGuiJyokyoHelp_C::ExecuteUbergraph_BP_BtlGuiJyokyoHelp(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiJyokyoHelp_C", "ExecuteUbergraph_BP_BtlGuiJyokyoHelp");

	Params::BP_BtlGuiJyokyoHelp_C_ExecuteUbergraph_BP_BtlGuiJyokyoHelp Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlGuiJyokyoHelp.BP_BtlGuiJyokyoHelp_C.Start
// (BlueprintCallable, BlueprintEvent)

void ABP_BtlGuiJyokyoHelp_C::Start()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiJyokyoHelp_C", "Start");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlGuiJyokyoHelp.BP_BtlGuiJyokyoHelp_C.GuiActorUpdate
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BtlGuiJyokyoHelp_C::GuiActorUpdate(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiJyokyoHelp_C", "GuiActorUpdate");

	Params::BP_BtlGuiJyokyoHelp_C_GuiActorUpdate Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlGuiJyokyoHelp.BP_BtlGuiJyokyoHelp_C.StartFadeOUT
// (BlueprintCallable, BlueprintEvent)

void ABP_BtlGuiJyokyoHelp_C::StartFadeOUT()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiJyokyoHelp_C", "StartFadeOUT");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlGuiJyokyoHelp.BP_BtlGuiJyokyoHelp_C.Start Fade In
// (BlueprintCallable, BlueprintEvent)

void ABP_BtlGuiJyokyoHelp_C::Start_Fade_In()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiJyokyoHelp_C", "Start Fade In");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlGuiJyokyoHelp.BP_BtlGuiJyokyoHelp_C.Fade out__UpdateFunc
// (BlueprintEvent)

void ABP_BtlGuiJyokyoHelp_C::Fade_out__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiJyokyoHelp_C", "Fade out__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlGuiJyokyoHelp.BP_BtlGuiJyokyoHelp_C.Fade out__FinishedFunc
// (BlueprintEvent)

void ABP_BtlGuiJyokyoHelp_C::Fade_out__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiJyokyoHelp_C", "Fade out__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlGuiJyokyoHelp.BP_BtlGuiJyokyoHelp_C.Fade In__UpdateFunc
// (BlueprintEvent)

void ABP_BtlGuiJyokyoHelp_C::Fade_In__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiJyokyoHelp_C", "Fade In__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlGuiJyokyoHelp.BP_BtlGuiJyokyoHelp_C.Fade In__FinishedFunc
// (BlueprintEvent)

void ABP_BtlGuiJyokyoHelp_C::Fade_In__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiJyokyoHelp_C", "Fade In__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlGuiJyokyoHelp.BP_BtlGuiJyokyoHelp_C.SetParam
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_BtlGuiIcon_C*                 BtlGuiIcon_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   genus_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ID_0                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   msgNo_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   var1_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   var2_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   renderTime_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   DelayTime_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   flags_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BtlGuiJyokyoHelp_C::SetParam(class ABP_BtlGuiIcon_C* BtlGuiIcon_0, int32 genus_0, int32 ID_0, int32 msgNo_0, int32 var1_0, int32 var2_0, float renderTime_0, float DelayTime_0, int32 flags_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiJyokyoHelp_C", "SetParam");

	Params::BP_BtlGuiJyokyoHelp_C_SetParam Parms{};

	Parms.BtlGuiIcon_0 = BtlGuiIcon_0;
	Parms.genus_0 = genus_0;
	Parms.ID_0 = ID_0;
	Parms.msgNo_0 = msgNo_0;
	Parms.var1_0 = var1_0;
	Parms.var2_0 = var2_0;
	Parms.renderTime_0 = renderTime_0;
	Parms.DelayTime_0 = DelayTime_0;
	Parms.flags_0 = flags_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlGuiJyokyoHelp.BP_BtlGuiJyokyoHelp_C.Update
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_BtlGuiJyokyoHelp_C::Update()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiJyokyoHelp_C", "Update");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlGuiJyokyoHelp.BP_BtlGuiJyokyoHelp_C.ClearAlpha
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_BtlGuiJyokyoHelp_C::ClearAlpha()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiJyokyoHelp_C", "ClearAlpha");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlGuiJyokyoHelp.BP_BtlGuiJyokyoHelp_C.ChangeWindow
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_BtlGuiJyokyoHelp_C::ChangeWindow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiJyokyoHelp_C", "ChangeWindow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlGuiJyokyoHelp.BP_BtlGuiJyokyoHelp_C.CalcAlpha
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   Alpha                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   fadeParam                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8*                                  calcedAlpha                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BtlGuiJyokyoHelp_C::CalcAlpha(float Alpha, float fadeParam, uint8* calcedAlpha)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiJyokyoHelp_C", "CalcAlpha");

	Params::BP_BtlGuiJyokyoHelp_C_CalcAlpha Parms{};

	Parms.Alpha = Alpha;
	Parms.fadeParam = fadeParam;

	UObject::ProcessEvent(Func, &Parms);

	if (calcedAlpha != nullptr)
		*calcedAlpha = Parms.calcedAlpha;
}


// Function BP_BtlGuiJyokyoHelp.BP_BtlGuiJyokyoHelp_C.Calc Alpha by Color
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FColor&                    In                                                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   fadeParam                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FColor*                          Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BtlGuiJyokyoHelp_C::Calc_Alpha_by_Color(const struct FColor& In, float fadeParam, struct FColor* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlGuiJyokyoHelp_C", "Calc Alpha by Color");

	Params::BP_BtlGuiJyokyoHelp_C_Calc_Alpha_by_Color Parms{};

	Parms.In = std::move(In);
	Parms.fadeParam = fadeParam;

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = std::move(Parms.Out);
}

}

