#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StaffRollDraw

#include "Basic.hpp"

#include "BP_StaffRollDraw_classes.hpp"
#include "BP_StaffRollDraw_parameters.hpp"


namespace SDK
{

// Function BP_StaffRollDraw.BP_StaffRollDraw_C.ExecuteUbergraph_BP_StaffRollDraw
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_StaffRollDraw_C::ExecuteUbergraph_BP_StaffRollDraw(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StaffRollDraw_C", "ExecuteUbergraph_BP_StaffRollDraw");

	Params::BP_StaffRollDraw_C_ExecuteUbergraph_BP_StaffRollDraw Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StaffRollDraw.BP_StaffRollDraw_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_StaffRollDraw_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StaffRollDraw_C", "ReceiveTick");

	Params::BP_StaffRollDraw_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StaffRollDraw.BP_StaffRollDraw_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_StaffRollDraw_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StaffRollDraw_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

