#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StaffRollDraw

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "xrd777_structs.hpp"
#include "xrd777_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_StaffRollDraw.BP_StaffRollDraw_C
// 0x0090 (0x3A7D0 - 0x3A740)
class ABP_StaffRollDraw_C final : public AStaffRollDraw
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x3A740(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x3A748(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FStaffRollTableData                    StaffRoll_Data;                                    // 0x3A750(0x0080)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_BP_StaffRollDraw(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_StaffRollDraw_C">();
	}
	static class ABP_StaffRollDraw_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_StaffRollDraw_C>();
	}
};
static_assert(alignof(ABP_StaffRollDraw_C) == 0x000008, "Wrong alignment on ABP_StaffRollDraw_C");
static_assert(sizeof(ABP_StaffRollDraw_C) == 0x03A7D0, "Wrong size on ABP_StaffRollDraw_C");
static_assert(offsetof(ABP_StaffRollDraw_C, UberGraphFrame) == 0x03A740, "Member 'ABP_StaffRollDraw_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_StaffRollDraw_C, DefaultSceneRoot) == 0x03A748, "Member 'ABP_StaffRollDraw_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(ABP_StaffRollDraw_C, StaffRoll_Data) == 0x03A750, "Member 'ABP_StaffRollDraw_C::StaffRoll_Data' has a wrong offset!");

}

