#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TutrialWindow

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_TutrialWindow.BP_TutrialWindow_C.ExecuteUbergraph_BP_TutrialWindow
// 0x0008 (0x0008 - 0x0000)
struct BP_TutrialWindow_C_ExecuteUbergraph_BP_TutrialWindow final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_TutrialWindow_C_ExecuteUbergraph_BP_TutrialWindow) == 0x000004, "Wrong alignment on BP_TutrialWindow_C_ExecuteUbergraph_BP_TutrialWindow");
static_assert(sizeof(BP_TutrialWindow_C_ExecuteUbergraph_BP_TutrialWindow) == 0x000008, "Wrong size on BP_TutrialWindow_C_ExecuteUbergraph_BP_TutrialWindow");
static_assert(offsetof(BP_TutrialWindow_C_ExecuteUbergraph_BP_TutrialWindow, EntryPoint) == 0x000000, "Member 'BP_TutrialWindow_C_ExecuteUbergraph_BP_TutrialWindow::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_TutrialWindow_C_ExecuteUbergraph_BP_TutrialWindow, K2Node_Event_DeltaSeconds) == 0x000004, "Member 'BP_TutrialWindow_C_ExecuteUbergraph_BP_TutrialWindow::K2Node_Event_DeltaSeconds' has a wrong offset!");

// Function BP_TutrialWindow.BP_TutrialWindow_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_TutrialWindow_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_TutrialWindow_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_TutrialWindow_C_ReceiveTick");
static_assert(sizeof(BP_TutrialWindow_C_ReceiveTick) == 0x000004, "Wrong size on BP_TutrialWindow_C_ReceiveTick");
static_assert(offsetof(BP_TutrialWindow_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_TutrialWindow_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

}

