#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TutrialWindow

#include "Basic.hpp"

#include "BP_TutrialWindow_classes.hpp"
#include "BP_TutrialWindow_parameters.hpp"


namespace SDK
{

// Function BP_TutrialWindow.BP_TutrialWindow_C.ExecuteUbergraph_BP_TutrialWindow
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TutrialWindow_C::ExecuteUbergraph_BP_TutrialWindow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TutrialWindow_C", "ExecuteUbergraph_BP_TutrialWindow");

	Params::BP_TutrialWindow_C_ExecuteUbergraph_BP_TutrialWindow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TutrialWindow.BP_TutrialWindow_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TutrialWindow_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TutrialWindow_C", "ReceiveTick");

	Params::BP_TutrialWindow_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TutrialWindow.BP_TutrialWindow_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_TutrialWindow_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TutrialWindow_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

