#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TutrialWindow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "xrd777_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TutrialWindow.BP_TutrialWindow_C
// 0x0010 (0x0538 - 0x0528)
class ABP_TutrialWindow_C final : public AitfMsgProgWindow_TUTRIALDraw
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0528(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0530(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_TutrialWindow(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_TutrialWindow_C">();
	}
	static class ABP_TutrialWindow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_TutrialWindow_C>();
	}
};
static_assert(alignof(ABP_TutrialWindow_C) == 0x000008, "Wrong alignment on ABP_TutrialWindow_C");
static_assert(sizeof(ABP_TutrialWindow_C) == 0x000538, "Wrong size on ABP_TutrialWindow_C");
static_assert(offsetof(ABP_TutrialWindow_C, UberGraphFrame) == 0x000528, "Member 'ABP_TutrialWindow_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_TutrialWindow_C, DefaultSceneRoot) == 0x000530, "Member 'ABP_TutrialWindow_C::DefaultSceneRoot' has a wrong offset!");

}

