#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_AtlEvtActor

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_AtlEvtActor.BPI_AtlEvtActor_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_AtlEvtActor_C final
{
public:
	void BPIResetAtlEvtLocomotionParams();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_AtlEvtActor_C">();
	}
	static class IBPI_AtlEvtActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_AtlEvtActor_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_AtlEvtActor_C) == 0x000001, "Wrong alignment on IBPI_AtlEvtActor_C");
static_assert(sizeof(IBPI_AtlEvtActor_C) == 0x000001, "Wrong size on IBPI_AtlEvtActor_C");

}

