#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_BtlGuiContactor

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_BtlGuiContactor.BPI_BtlGuiContactor_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_BtlGuiContactor_C final
{
public:
	void FinishAlloutActor();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_BtlGuiContactor_C">();
	}
	static class IBPI_BtlGuiContactor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_BtlGuiContactor_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_BtlGuiContactor_C) == 0x000001, "Wrong alignment on IBPI_BtlGuiContactor_C");
static_assert(sizeof(IBPI_BtlGuiContactor_C) == 0x000001, "Wrong size on IBPI_BtlGuiContactor_C");

}

