#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_FLDSky

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_FLDSky.BPI_FLDSky_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_FLDSky_C final
{
public:
	void GetDirectionalLightMoon(class ULightComponent** LightComponent);
	void FLDSkyReset();
	void GetExposureCompensation(float* Exposure);
	void SetExposureCompensation(float Exposure);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_FLDSky_C">();
	}
	static class IBPI_FLDSky_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_FLDSky_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_FLDSky_C) == 0x000001, "Wrong alignment on IBPI_FLDSky_C");
static_assert(sizeof(IBPI_FLDSky_C) == 0x000001, "Wrong size on IBPI_FLDSky_C");

}

