#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_Get_PC0001_Variables

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_Get_PC0001_Variables.BPI_Get_PC0001_Variables_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_Get_PC0001_Variables_C final
{
public:
	void Is_EventPlayAndHaveBag(bool* Out_Result);
	void Get_ForceAttachPocket(bool* Out_ForceAttachPocket);
	void Get_IsAttachedBostonBag(bool* Out_IsAttachedBostonBag);
	void Get_NotUpdateAttachPocket(bool* Out_NotUpdateEnableAttachPocket);
	void Get_AttachPocketAlpha(float* Out_AttachPocket_L_Alpha, float* Out_AttachPocket_R_Alpha);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_Get_PC0001_Variables_C">();
	}
	static class IBPI_Get_PC0001_Variables_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_Get_PC0001_Variables_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_Get_PC0001_Variables_C) == 0x000001, "Wrong alignment on IBPI_Get_PC0001_Variables_C");
static_assert(sizeof(IBPI_Get_PC0001_Variables_C) == 0x000001, "Wrong size on IBPI_Get_PC0001_Variables_C");

}

