#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_BtlCharacterContactor

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_BtlCharacterContactor.BPI_BtlCharacterContactor_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_BtlCharacterContactor_C final
{
public:
	void CheckNyxCoreMode(bool* NyxCoreMode);
	void EncountHeroRunStop();
	void EncountHeroRunStart(float StartAnimationTime);
	void EncountHeroGetShowActor(TArray<class AActor*>* ShowActors);
	void CheckSkeletalMeshValid(bool* IsValid);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_BtlCharacterContactor_C">();
	}
	static class IBPI_BtlCharacterContactor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_BtlCharacterContactor_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_BtlCharacterContactor_C) == 0x000001, "Wrong alignment on IBPI_BtlCharacterContactor_C");
static_assert(sizeof(IBPI_BtlCharacterContactor_C) == 0x000001, "Wrong size on IBPI_BtlCharacterContactor_C");

}

