#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: McaAssetPlugin

#include "Basic.hpp"


namespace SDK
{

// ScriptStruct McaAssetPlugin.McaCamData
// 0x0020 (0x0020 - 0x0000)
struct FMcaCamData final
{
public:
	float                                         tx;                                                // 0x0000(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ty;                                                // 0x0004(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         tz;                                                // 0x0008(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         rx;                                                // 0x000C(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ry;                                                // 0x0010(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         rz;                                                // 0x0014(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         fovX;                                              // 0x0018(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         fovY;                                              // 0x001C(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FMcaCamData) == 0x000004, "Wrong alignment on FMcaCamData");
static_assert(sizeof(FMcaCamData) == 0x000020, "Wrong size on FMcaCamData");
static_assert(offsetof(FMcaCamData, tx) == 0x000000, "Member 'FMcaCamData::tx' has a wrong offset!");
static_assert(offsetof(FMcaCamData, ty) == 0x000004, "Member 'FMcaCamData::ty' has a wrong offset!");
static_assert(offsetof(FMcaCamData, tz) == 0x000008, "Member 'FMcaCamData::tz' has a wrong offset!");
static_assert(offsetof(FMcaCamData, rx) == 0x00000C, "Member 'FMcaCamData::rx' has a wrong offset!");
static_assert(offsetof(FMcaCamData, ry) == 0x000010, "Member 'FMcaCamData::ry' has a wrong offset!");
static_assert(offsetof(FMcaCamData, rz) == 0x000014, "Member 'FMcaCamData::rz' has a wrong offset!");
static_assert(offsetof(FMcaCamData, fovX) == 0x000018, "Member 'FMcaCamData::fovX' has a wrong offset!");
static_assert(offsetof(FMcaCamData, fovY) == 0x00001C, "Member 'FMcaCamData::fovY' has a wrong offset!");

// ScriptStruct McaAssetPlugin.McaData
// 0x0020 (0x0020 - 0x0000)
struct FMcaData final
{
public:
	uint32                                        frameSkip;                                         // 0x0000(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         frameNum;                                          // 0x0004(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         dataFormat;                                        // 0x0008(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FMcaCamData>                    pCamData;                                          // 0x0010(0x0010)(Edit, ZeroConstructor, EditConst, NativeAccessSpecifierPublic)
};
static_assert(alignof(FMcaData) == 0x000008, "Wrong alignment on FMcaData");
static_assert(sizeof(FMcaData) == 0x000020, "Wrong size on FMcaData");
static_assert(offsetof(FMcaData, frameSkip) == 0x000000, "Member 'FMcaData::frameSkip' has a wrong offset!");
static_assert(offsetof(FMcaData, frameNum) == 0x000004, "Member 'FMcaData::frameNum' has a wrong offset!");
static_assert(offsetof(FMcaData, dataFormat) == 0x000008, "Member 'FMcaData::dataFormat' has a wrong offset!");
static_assert(offsetof(FMcaData, pCamData) == 0x000010, "Member 'FMcaData::pCamData' has a wrong offset!");

}

