#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlatformSystemHelper

#include "Basic.hpp"

#include "PlatformSystemHelper_classes.hpp"
#include "PlatformSystemHelper_parameters.hpp"


namespace SDK
{

// Function PlatformSystemHelper.PlatformSystemHelperFuncLib.ShowStoreUI
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class UObject*                    WorldContextObject                                     (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    InTitleId                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlatformSystemHelperFuncLib::ShowStoreUI(const class UObject* WorldContextObject, const class FString& InTitleId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("PlatformSystemHelperFuncLib", "ShowStoreUI");

	Params::PlatformSystemHelperFuncLib_ShowStoreUI Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.InTitleId = std::move(InTitleId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

