#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlatformSystemHelper

#include "Basic.hpp"


namespace SDK::Params
{

// Function PlatformSystemHelper.PlatformSystemHelperFuncLib.ShowStoreUI
// 0x0018 (0x0018 - 0x0000)
struct PlatformSystemHelperFuncLib_ShowStoreUI final
{
public:
	const class UObject*                          WorldContextObject;                                // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 InTitleId;                                         // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlatformSystemHelperFuncLib_ShowStoreUI) == 0x000008, "Wrong alignment on PlatformSystemHelperFuncLib_ShowStoreUI");
static_assert(sizeof(PlatformSystemHelperFuncLib_ShowStoreUI) == 0x000018, "Wrong size on PlatformSystemHelperFuncLib_ShowStoreUI");
static_assert(offsetof(PlatformSystemHelperFuncLib_ShowStoreUI, WorldContextObject) == 0x000000, "Member 'PlatformSystemHelperFuncLib_ShowStoreUI::WorldContextObject' has a wrong offset!");
static_assert(offsetof(PlatformSystemHelperFuncLib_ShowStoreUI, InTitleId) == 0x000008, "Member 'PlatformSystemHelperFuncLib_ShowStoreUI::InTitleId' has a wrong offset!");

}

