#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlatformSystemHelper

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class PlatformSystemHelper.ExtraLoadGameSystem
// 0x0000 (0x0028 - 0x0028)
class UExtraLoadGameSystem : public UObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ExtraLoadGameSystem">();
	}
	static class UExtraLoadGameSystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UExtraLoadGameSystem>();
	}
};
static_assert(alignof(UExtraLoadGameSystem) == 0x000008, "Wrong alignment on UExtraLoadGameSystem");
static_assert(sizeof(UExtraLoadGameSystem) == 0x000028, "Wrong size on UExtraLoadGameSystem");

// Class PlatformSystemHelper.PlatformSystemHelperFuncLib
// 0x0000 (0x0028 - 0x0028)
class UPlatformSystemHelperFuncLib final : public UBlueprintFunctionLibrary
{
public:
	static void ShowStoreUI(const class UObject* WorldContextObject, const class FString& InTitleId);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PlatformSystemHelperFuncLib">();
	}
	static class UPlatformSystemHelperFuncLib* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlatformSystemHelperFuncLib>();
	}
};
static_assert(alignof(UPlatformSystemHelperFuncLib) == 0x000008, "Wrong alignment on UPlatformSystemHelperFuncLib");
static_assert(sizeof(UPlatformSystemHelperFuncLib) == 0x000028, "Wrong size on UPlatformSystemHelperFuncLib");

// Class PlatformSystemHelper.SteamExtraLoadGameSystem
// 0x0000 (0x0028 - 0x0028)
class USteamExtraLoadGameSystem final : public UExtraLoadGameSystem
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SteamExtraLoadGameSystem">();
	}
	static class USteamExtraLoadGameSystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<USteamExtraLoadGameSystem>();
	}
};
static_assert(alignof(USteamExtraLoadGameSystem) == 0x000008, "Wrong alignment on USteamExtraLoadGameSystem");
static_assert(sizeof(USteamExtraLoadGameSystem) == 0x000028, "Wrong size on USteamExtraLoadGameSystem");

// Class PlatformSystemHelper.StoreUISystem
// 0x0000 (0x0028 - 0x0028)
class UStoreUISystem : public UObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"StoreUISystem">();
	}
	static class UStoreUISystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStoreUISystem>();
	}
};
static_assert(alignof(UStoreUISystem) == 0x000008, "Wrong alignment on UStoreUISystem");
static_assert(sizeof(UStoreUISystem) == 0x000028, "Wrong size on UStoreUISystem");

// Class PlatformSystemHelper.SteamStoreUISystem
// 0x0000 (0x0028 - 0x0028)
class USteamStoreUISystem final : public UStoreUISystem
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SteamStoreUISystem">();
	}
	static class USteamStoreUISystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<USteamStoreUISystem>();
	}
};
static_assert(alignof(USteamStoreUISystem) == 0x000008, "Wrong alignment on USteamStoreUISystem");
static_assert(sizeof(USteamStoreUISystem) == 0x000028, "Wrong size on USteamStoreUISystem");

}

