#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SoundManager

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "Engine_classes.hpp"
#include "SoundManager_structs.hpp"


namespace SDK
{

// Class SoundManager.AsyncCueSheetManager
// 0x0038 (0x0060 - 0x0028)
class UAsyncCueSheetManager final : public UObject
{
public:
	TMulticastInlineDelegate<void()>              OnLoadCompleted;                                   // 0x0028(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnLoadFailed;                                      // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	class USoundAtomCueSheet*                     CueSheet;                                          // 0x0048(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_50[0x10];                                      // 0x0050(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	class USoundAtomCueSheet* GetAtomCueSheet();
	void LoadAsync(const struct FSoftObjectPath& PathForCueSheet);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AsyncCueSheetManager">();
	}
	static class UAsyncCueSheetManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAsyncCueSheetManager>();
	}
};
static_assert(alignof(UAsyncCueSheetManager) == 0x000008, "Wrong alignment on UAsyncCueSheetManager");
static_assert(sizeof(UAsyncCueSheetManager) == 0x000060, "Wrong size on UAsyncCueSheetManager");
static_assert(offsetof(UAsyncCueSheetManager, OnLoadCompleted) == 0x000028, "Member 'UAsyncCueSheetManager::OnLoadCompleted' has a wrong offset!");
static_assert(offsetof(UAsyncCueSheetManager, OnLoadFailed) == 0x000038, "Member 'UAsyncCueSheetManager::OnLoadFailed' has a wrong offset!");
static_assert(offsetof(UAsyncCueSheetManager, CueSheet) == 0x000048, "Member 'UAsyncCueSheetManager::CueSheet' has a wrong offset!");

// Class SoundManager.LiveLipSync
// 0x0008 (0x0030 - 0x0028)
class ULiveLipSync final : public UObject
{
public:
	class ULipsAtomAnalyzer*                      LipsAnalyzer;                                      // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	bool attachSoundManager(int32 majNum, int32 minNum);
	bool detachSoundManager(int32 majNum, int32 minNum);
	struct FCriLipsMouthInfo getLipsyncLiveInfo();
	struct FCriLipsMorphTargetBlendAmountAsJapanese getLipsyncLiveJapanese();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LiveLipSync">();
	}
	static class ULiveLipSync* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULiveLipSync>();
	}
};
static_assert(alignof(ULiveLipSync) == 0x000008, "Wrong alignment on ULiveLipSync");
static_assert(sizeof(ULiveLipSync) == 0x000030, "Wrong size on ULiveLipSync");
static_assert(offsetof(ULiveLipSync, LipsAnalyzer) == 0x000028, "Member 'ULiveLipSync::LipsAnalyzer' has a wrong offset!");

// Class SoundManager.PlayerControlBlock
// 0x0078 (0x00A0 - 0x0028)
class UPlayerControlBlock final : public UObject
{
public:
	class UAtomComponent*                         Player;                                            // 0x0028(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_30[0x60];                                      // 0x0030(0x0060)(Fixing Size After Last Property [ Dumper-7 ])
	class ULipsAtomAnalyzer*                      LipsAnalyzer;                                      // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_98[0x8];                                       // 0x0098(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PlayerControlBlock">();
	}
	static class UPlayerControlBlock* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerControlBlock>();
	}
};
static_assert(alignof(UPlayerControlBlock) == 0x000008, "Wrong alignment on UPlayerControlBlock");
static_assert(sizeof(UPlayerControlBlock) == 0x0000A0, "Wrong size on UPlayerControlBlock");
static_assert(offsetof(UPlayerControlBlock, Player) == 0x000028, "Member 'UPlayerControlBlock::Player' has a wrong offset!");
static_assert(offsetof(UPlayerControlBlock, LipsAnalyzer) == 0x000090, "Member 'UPlayerControlBlock::LipsAnalyzer' has a wrong offset!");

// Class SoundManager.AcbFileControlBlock
// 0x0030 (0x0058 - 0x0028)
class UAcbFileControlBlock final : public UObject
{
public:
	uint8                                         Pad_28[0x18];                                      // 0x0028(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundAtomCueSheet*                     CueSheet;                                          // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UACBLoadObject*                         Loader;                                            // 0x0048(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x8];                                       // 0x0050(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AcbFileControlBlock">();
	}
	static class UAcbFileControlBlock* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAcbFileControlBlock>();
	}
};
static_assert(alignof(UAcbFileControlBlock) == 0x000008, "Wrong alignment on UAcbFileControlBlock");
static_assert(sizeof(UAcbFileControlBlock) == 0x000058, "Wrong size on UAcbFileControlBlock");
static_assert(offsetof(UAcbFileControlBlock, CueSheet) == 0x000040, "Member 'UAcbFileControlBlock::CueSheet' has a wrong offset!");
static_assert(offsetof(UAcbFileControlBlock, Loader) == 0x000048, "Member 'UAcbFileControlBlock::Loader' has a wrong offset!");

// Class SoundManager.PlayAdxControl
// 0x0A70 (0x0A98 - 0x0028)
class UPlayAdxControl final : public UObject
{
public:
	uint8                                         Pad_28[0x18];                                      // 0x0028(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	class UPlayerControlBlock*                    mPlayerControlBlock[0x100];                        // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UAcbFileControlBlock*                   mAcbFileControlBlock[0x40];                        // 0x0840(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_A40[0x58];                                     // 0x0A40(0x0058)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static int32 getNumCuePlayingCountByName(const class FString& Name_0);

	bool attachLipsyncLive(int32 majorNum, int32 minorNum);
	bool checkPauseSound(int32 PlayerMajorID, int32 PlayerMinorID);
	bool checkPlaying(int32 PlayerMajorID, int32 PlayerMinorID);
	int32 checkReadAcb(const class FString& Filename);
	bool checkReadEnd(int32 bankID);
	int32 createPlayerBank(int32 PlayerMajorID, int32 PlayerMinorID, bool isMulti);
	bool detachLipsyncLive(int32 majorNum, int32 minorNum);
	bool fadeInBGMCategorySoundmanager(int32 fadeInTime, float fadeInVolume);
	void fadeInSndMng(int32 PlayerMajorID, int32 PlayerMinorID, int32 fadeInTime);
	bool fadeOutBGMCategorySoundManager(int32 fadeOutTime, float fadeOutVolume);
	void fadeOutSndMng(int32 PlayerMajorID, int32 PlayerMinorID, int32 fadeOutTime);
	float getIntegratedLoudness();
	int64 getLengthPlayerBank(int32 majorNum, int32 minorNum, int32 CueId);
	int64 getLengthSoundBank(int32 bankID, int32 CueId);
	struct FCriLipsMouthInfo getLipsyncLiveInfo(int32 majorNum, int32 minorNum);
	struct FCriLipsMorphTargetBlendAmountAsJapanese getLipsyncLiveJapanese(int32 majorNum, int32 minorNum);
	float getMomentaryLoudness();
	float getShortLoudness();
	float GetTime(int32 PlayerMajorID, int32 PlayerMinorID);
	bool IsLoop(int32 PlayerMajorID, int32 PlayerMinorID);
	void pauseSound(int32 PlayerMajorID, int32 PlayerMinorID, bool flag);
	void releasePlayerBank(int32 PlayerMajorID, int32 PlayerMinorID);
	void requestFreeAcb(int32 bankID);
	int32 requestLoadAcb(const class FString& Filename);
	void requestSound(int32 PlayerMajorID, int32 PlayerMinorID, int32 CueId, bool isForceChange);
	void resetLoudness();
	void setPlayerAcbBank(int32 PlayerMajorID, int32 PlayerMinorID, EPlayerType Type, int32 bankID);
	void stopSound(int32 PlayerMajorID, int32 PlayerMinorID);
	void stopSound_IMD(int32 PlayerMajorID, int32 PlayerMinorID);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PlayAdxControl">();
	}
	static class UPlayAdxControl* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayAdxControl>();
	}
};
static_assert(alignof(UPlayAdxControl) == 0x000008, "Wrong alignment on UPlayAdxControl");
static_assert(sizeof(UPlayAdxControl) == 0x000A98, "Wrong size on UPlayAdxControl");
static_assert(offsetof(UPlayAdxControl, mPlayerControlBlock) == 0x000040, "Member 'UPlayAdxControl::mPlayerControlBlock' has a wrong offset!");
static_assert(offsetof(UPlayAdxControl, mAcbFileControlBlock) == 0x000840, "Member 'UPlayAdxControl::mAcbFileControlBlock' has a wrong offset!");

// Class SoundManager.ACBLoadObject
// 0x0010 (0x00C0 - 0x00B0)
class UACBLoadObject final : public UActorComponent
{
public:
	uint8                                         Pad_B0[0x8];                                       // 0x00B0(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UAsyncCueSheetManager*                  Loader;                                            // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void OnLoadCompleted();
	void OnLoadFailed();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ACBLoadObject">();
	}
	static class UACBLoadObject* GetDefaultObj()
	{
		return GetDefaultObjImpl<UACBLoadObject>();
	}
};
static_assert(alignof(UACBLoadObject) == 0x000008, "Wrong alignment on UACBLoadObject");
static_assert(sizeof(UACBLoadObject) == 0x0000C0, "Wrong size on UACBLoadObject");
static_assert(offsetof(UACBLoadObject, Loader) == 0x0000B8, "Member 'UACBLoadObject::Loader' has a wrong offset!");

// Class SoundManager.SoundManagerReadyAsyncFunction
// 0x0028 (0x0058 - 0x0030)
class USoundManagerReadyAsyncFunction final : public UBlueprintAsyncActionBase
{
public:
	TMulticastInlineDelegate<void(int32 Result)>  Completed;                                         // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_40[0x18];                                      // 0x0040(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class USoundManagerReadyAsyncFunction* SoundManagerReadyAsyncFunction(class UObject* WorldContextObject, class UPlayAdxControl* Control, int32 bankID);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SoundManagerReadyAsyncFunction">();
	}
	static class USoundManagerReadyAsyncFunction* GetDefaultObj()
	{
		return GetDefaultObjImpl<USoundManagerReadyAsyncFunction>();
	}
};
static_assert(alignof(USoundManagerReadyAsyncFunction) == 0x000008, "Wrong alignment on USoundManagerReadyAsyncFunction");
static_assert(sizeof(USoundManagerReadyAsyncFunction) == 0x000058, "Wrong size on USoundManagerReadyAsyncFunction");
static_assert(offsetof(USoundManagerReadyAsyncFunction, Completed) == 0x000030, "Member 'USoundManagerReadyAsyncFunction::Completed' has a wrong offset!");

// Class SoundManager.SoundManagerGameInstanceSubSystem
// 0x0010 (0x0040 - 0x0030)
class USoundManagerGameInstanceSubSystem final : public UGameInstanceSubsystem
{
public:
	class UPlayAdxControl*                        PlayAdxControl;                                    // 0x0030(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_38[0x8];                                       // 0x0038(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	class UPlayAdxControl* GetPlayAdxControl();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SoundManagerGameInstanceSubSystem">();
	}
	static class USoundManagerGameInstanceSubSystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<USoundManagerGameInstanceSubSystem>();
	}
};
static_assert(alignof(USoundManagerGameInstanceSubSystem) == 0x000008, "Wrong alignment on USoundManagerGameInstanceSubSystem");
static_assert(sizeof(USoundManagerGameInstanceSubSystem) == 0x000040, "Wrong size on USoundManagerGameInstanceSubSystem");
static_assert(offsetof(USoundManagerGameInstanceSubSystem, PlayAdxControl) == 0x000030, "Member 'USoundManagerGameInstanceSubSystem::PlayAdxControl' has a wrong offset!");

}

