#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SoundManager

#include "Basic.hpp"

#include "SoundManager_classes.hpp"
#include "SoundManager_parameters.hpp"


namespace SDK
{

// Function SoundManager.AsyncCueSheetManager.GetAtomCueSheet
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class USoundAtomCueSheet*               ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class USoundAtomCueSheet* UAsyncCueSheetManager::GetAtomCueSheet()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AsyncCueSheetManager", "GetAtomCueSheet");

	Params::AsyncCueSheetManager_GetAtomCueSheet Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.AsyncCueSheetManager.LoadAsync
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FSoftObjectPath&           PathForCueSheet                                        (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAsyncCueSheetManager::LoadAsync(const struct FSoftObjectPath& PathForCueSheet)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AsyncCueSheetManager", "LoadAsync");

	Params::AsyncCueSheetManager_LoadAsync Parms{};

	Parms.PathForCueSheet = std::move(PathForCueSheet);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SoundManager.LiveLipSync.attachSoundManager
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   majNum                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   minNum                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool ULiveLipSync::attachSoundManager(int32 majNum, int32 minNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LiveLipSync", "attachSoundManager");

	Params::LiveLipSync_attachSoundManager Parms{};

	Parms.majNum = majNum;
	Parms.minNum = minNum;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.LiveLipSync.detachSoundManager
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   majNum                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   minNum                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool ULiveLipSync::detachSoundManager(int32 majNum, int32 minNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LiveLipSync", "detachSoundManager");

	Params::LiveLipSync_detachSoundManager Parms{};

	Parms.majNum = majNum;
	Parms.minNum = minNum;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.LiveLipSync.getLipsyncLiveInfo
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// struct FCriLipsMouthInfo                ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

struct FCriLipsMouthInfo ULiveLipSync::getLipsyncLiveInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LiveLipSync", "getLipsyncLiveInfo");

	Params::LiveLipSync_getLipsyncLiveInfo Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.LiveLipSync.getLipsyncLiveJapanese
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// struct FCriLipsMorphTargetBlendAmountAsJapaneseReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

struct FCriLipsMorphTargetBlendAmountAsJapanese ULiveLipSync::getLipsyncLiveJapanese()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LiveLipSync", "getLipsyncLiveJapanese");

	Params::LiveLipSync_getLipsyncLiveJapanese Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.getNumCuePlayingCountByName
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class FString&                    Name_0                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPlayAdxControl::getNumCuePlayingCountByName(const class FString& Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("PlayAdxControl", "getNumCuePlayingCountByName");

	Params::PlayAdxControl_getNumCuePlayingCountByName Parms{};

	Parms.Name_0 = std::move(Name_0);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.attachLipsyncLive
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   majorNum                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   minorNum                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPlayAdxControl::attachLipsyncLive(int32 majorNum, int32 minorNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "attachLipsyncLive");

	Params::PlayAdxControl_attachLipsyncLive Parms{};

	Parms.majorNum = majorNum;
	Parms.minorNum = minorNum;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.checkPauseSound
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   PlayerMajorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   PlayerMinorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPlayAdxControl::checkPauseSound(int32 PlayerMajorID, int32 PlayerMinorID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "checkPauseSound");

	Params::PlayAdxControl_checkPauseSound Parms{};

	Parms.PlayerMajorID = PlayerMajorID;
	Parms.PlayerMinorID = PlayerMinorID;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.checkPlaying
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   PlayerMajorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   PlayerMinorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPlayAdxControl::checkPlaying(int32 PlayerMajorID, int32 PlayerMinorID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "checkPlaying");

	Params::PlayAdxControl_checkPlaying Parms{};

	Parms.PlayerMajorID = PlayerMajorID;
	Parms.PlayerMinorID = PlayerMinorID;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.checkReadAcb
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    Filename                                               (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPlayAdxControl::checkReadAcb(const class FString& Filename)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "checkReadAcb");

	Params::PlayAdxControl_checkReadAcb Parms{};

	Parms.Filename = std::move(Filename);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.checkReadEnd
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   bankID                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPlayAdxControl::checkReadEnd(int32 bankID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "checkReadEnd");

	Params::PlayAdxControl_checkReadEnd Parms{};

	Parms.bankID = bankID;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.createPlayerBank
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   PlayerMajorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   PlayerMinorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    isMulti                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPlayAdxControl::createPlayerBank(int32 PlayerMajorID, int32 PlayerMinorID, bool isMulti)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "createPlayerBank");

	Params::PlayAdxControl_createPlayerBank Parms{};

	Parms.PlayerMajorID = PlayerMajorID;
	Parms.PlayerMinorID = PlayerMinorID;
	Parms.isMulti = isMulti;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.detachLipsyncLive
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   majorNum                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   minorNum                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPlayAdxControl::detachLipsyncLive(int32 majorNum, int32 minorNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "detachLipsyncLive");

	Params::PlayAdxControl_detachLipsyncLive Parms{};

	Parms.majorNum = majorNum;
	Parms.minorNum = minorNum;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.fadeInBGMCategorySoundmanager
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   fadeInTime                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   fadeInVolume                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPlayAdxControl::fadeInBGMCategorySoundmanager(int32 fadeInTime, float fadeInVolume)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "fadeInBGMCategorySoundmanager");

	Params::PlayAdxControl_fadeInBGMCategorySoundmanager Parms{};

	Parms.fadeInTime = fadeInTime;
	Parms.fadeInVolume = fadeInVolume;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.fadeInSndMng
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   PlayerMajorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   PlayerMinorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   fadeInTime                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayAdxControl::fadeInSndMng(int32 PlayerMajorID, int32 PlayerMinorID, int32 fadeInTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "fadeInSndMng");

	Params::PlayAdxControl_fadeInSndMng Parms{};

	Parms.PlayerMajorID = PlayerMajorID;
	Parms.PlayerMinorID = PlayerMinorID;
	Parms.fadeInTime = fadeInTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SoundManager.PlayAdxControl.fadeOutBGMCategorySoundManager
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   fadeOutTime                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   fadeOutVolume                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPlayAdxControl::fadeOutBGMCategorySoundManager(int32 fadeOutTime, float fadeOutVolume)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "fadeOutBGMCategorySoundManager");

	Params::PlayAdxControl_fadeOutBGMCategorySoundManager Parms{};

	Parms.fadeOutTime = fadeOutTime;
	Parms.fadeOutVolume = fadeOutVolume;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.fadeOutSndMng
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   PlayerMajorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   PlayerMinorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   fadeOutTime                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayAdxControl::fadeOutSndMng(int32 PlayerMajorID, int32 PlayerMinorID, int32 fadeOutTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "fadeOutSndMng");

	Params::PlayAdxControl_fadeOutSndMng Parms{};

	Parms.PlayerMajorID = PlayerMajorID;
	Parms.PlayerMinorID = PlayerMinorID;
	Parms.fadeOutTime = fadeOutTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SoundManager.PlayAdxControl.getIntegratedLoudness
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UPlayAdxControl::getIntegratedLoudness()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "getIntegratedLoudness");

	Params::PlayAdxControl_getIntegratedLoudness Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.getLengthPlayerBank
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   majorNum                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   minorNum                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   CueId                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int64                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int64 UPlayAdxControl::getLengthPlayerBank(int32 majorNum, int32 minorNum, int32 CueId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "getLengthPlayerBank");

	Params::PlayAdxControl_getLengthPlayerBank Parms{};

	Parms.majorNum = majorNum;
	Parms.minorNum = minorNum;
	Parms.CueId = CueId;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.getLengthSoundBank
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   bankID                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   CueId                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int64                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int64 UPlayAdxControl::getLengthSoundBank(int32 bankID, int32 CueId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "getLengthSoundBank");

	Params::PlayAdxControl_getLengthSoundBank Parms{};

	Parms.bankID = bankID;
	Parms.CueId = CueId;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.getLipsyncLiveInfo
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   majorNum                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   minorNum                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FCriLipsMouthInfo                ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

struct FCriLipsMouthInfo UPlayAdxControl::getLipsyncLiveInfo(int32 majorNum, int32 minorNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "getLipsyncLiveInfo");

	Params::PlayAdxControl_getLipsyncLiveInfo Parms{};

	Parms.majorNum = majorNum;
	Parms.minorNum = minorNum;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.getLipsyncLiveJapanese
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   majorNum                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   minorNum                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FCriLipsMorphTargetBlendAmountAsJapaneseReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

struct FCriLipsMorphTargetBlendAmountAsJapanese UPlayAdxControl::getLipsyncLiveJapanese(int32 majorNum, int32 minorNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "getLipsyncLiveJapanese");

	Params::PlayAdxControl_getLipsyncLiveJapanese Parms{};

	Parms.majorNum = majorNum;
	Parms.minorNum = minorNum;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.getMomentaryLoudness
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UPlayAdxControl::getMomentaryLoudness()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "getMomentaryLoudness");

	Params::PlayAdxControl_getMomentaryLoudness Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.getShortLoudness
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UPlayAdxControl::getShortLoudness()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "getShortLoudness");

	Params::PlayAdxControl_getShortLoudness Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.GetTime
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   PlayerMajorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   PlayerMinorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UPlayAdxControl::GetTime(int32 PlayerMajorID, int32 PlayerMinorID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "GetTime");

	Params::PlayAdxControl_GetTime Parms{};

	Parms.PlayerMajorID = PlayerMajorID;
	Parms.PlayerMinorID = PlayerMinorID;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.IsLoop
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   PlayerMajorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   PlayerMinorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPlayAdxControl::IsLoop(int32 PlayerMajorID, int32 PlayerMinorID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "IsLoop");

	Params::PlayAdxControl_IsLoop Parms{};

	Parms.PlayerMajorID = PlayerMajorID;
	Parms.PlayerMinorID = PlayerMinorID;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.pauseSound
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   PlayerMajorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   PlayerMinorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    flag                                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayAdxControl::pauseSound(int32 PlayerMajorID, int32 PlayerMinorID, bool flag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "pauseSound");

	Params::PlayAdxControl_pauseSound Parms{};

	Parms.PlayerMajorID = PlayerMajorID;
	Parms.PlayerMinorID = PlayerMinorID;
	Parms.flag = flag;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SoundManager.PlayAdxControl.releasePlayerBank
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   PlayerMajorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   PlayerMinorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayAdxControl::releasePlayerBank(int32 PlayerMajorID, int32 PlayerMinorID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "releasePlayerBank");

	Params::PlayAdxControl_releasePlayerBank Parms{};

	Parms.PlayerMajorID = PlayerMajorID;
	Parms.PlayerMinorID = PlayerMinorID;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SoundManager.PlayAdxControl.requestFreeAcb
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   bankID                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayAdxControl::requestFreeAcb(int32 bankID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "requestFreeAcb");

	Params::PlayAdxControl_requestFreeAcb Parms{};

	Parms.bankID = bankID;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SoundManager.PlayAdxControl.requestLoadAcb
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    Filename                                               (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPlayAdxControl::requestLoadAcb(const class FString& Filename)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "requestLoadAcb");

	Params::PlayAdxControl_requestLoadAcb Parms{};

	Parms.Filename = std::move(Filename);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.PlayAdxControl.requestSound
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   PlayerMajorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   PlayerMinorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   CueId                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    isForceChange                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayAdxControl::requestSound(int32 PlayerMajorID, int32 PlayerMinorID, int32 CueId, bool isForceChange)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "requestSound");

	Params::PlayAdxControl_requestSound Parms{};

	Parms.PlayerMajorID = PlayerMajorID;
	Parms.PlayerMinorID = PlayerMinorID;
	Parms.CueId = CueId;
	Parms.isForceChange = isForceChange;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SoundManager.PlayAdxControl.resetLoudness
// (Final, Native, Public, BlueprintCallable)

void UPlayAdxControl::resetLoudness()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "resetLoudness");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function SoundManager.PlayAdxControl.setPlayerAcbBank
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   PlayerMajorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   PlayerMinorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EPlayerType                             Type                                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   bankID                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayAdxControl::setPlayerAcbBank(int32 PlayerMajorID, int32 PlayerMinorID, EPlayerType Type, int32 bankID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "setPlayerAcbBank");

	Params::PlayAdxControl_setPlayerAcbBank Parms{};

	Parms.PlayerMajorID = PlayerMajorID;
	Parms.PlayerMinorID = PlayerMinorID;
	Parms.Type = Type;
	Parms.bankID = bankID;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SoundManager.PlayAdxControl.stopSound
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   PlayerMajorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   PlayerMinorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayAdxControl::stopSound(int32 PlayerMajorID, int32 PlayerMinorID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "stopSound");

	Params::PlayAdxControl_stopSound Parms{};

	Parms.PlayerMajorID = PlayerMajorID;
	Parms.PlayerMinorID = PlayerMinorID;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SoundManager.PlayAdxControl.stopSound_IMD
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   PlayerMajorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   PlayerMinorID                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayAdxControl::stopSound_IMD(int32 PlayerMajorID, int32 PlayerMinorID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayAdxControl", "stopSound_IMD");

	Params::PlayAdxControl_stopSound_IMD Parms{};

	Parms.PlayerMajorID = PlayerMajorID;
	Parms.PlayerMinorID = PlayerMinorID;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SoundManager.ACBLoadObject.OnLoadCompleted
// (Final, Native, Protected, BlueprintCallable)

void UACBLoadObject::OnLoadCompleted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ACBLoadObject", "OnLoadCompleted");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function SoundManager.ACBLoadObject.OnLoadFailed
// (Final, Native, Protected, BlueprintCallable)

void UACBLoadObject::OnLoadFailed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ACBLoadObject", "OnLoadFailed");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function SoundManager.SoundManagerReadyAsyncFunction.SoundManagerReadyAsyncFunction
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UPlayAdxControl*                  Control                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   bankID                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class USoundManagerReadyAsyncFunction*  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class USoundManagerReadyAsyncFunction* USoundManagerReadyAsyncFunction::SoundManagerReadyAsyncFunction(class UObject* WorldContextObject, class UPlayAdxControl* Control, int32 bankID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SoundManagerReadyAsyncFunction", "SoundManagerReadyAsyncFunction");

	Params::SoundManagerReadyAsyncFunction_SoundManagerReadyAsyncFunction Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.Control = Control;
	Parms.bankID = bankID;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SoundManager.SoundManagerGameInstanceSubSystem.GetPlayAdxControl
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UPlayAdxControl*                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UPlayAdxControl* USoundManagerGameInstanceSubSystem::GetPlayAdxControl()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundManagerGameInstanceSubSystem", "GetPlayAdxControl");

	Params::SoundManagerGameInstanceSubSystem_GetPlayAdxControl Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

