#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SoundManager

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "CriWareAdxLipSync_structs.hpp"
#include "SoundManager_structs.hpp"


namespace SDK::Params
{

// Function SoundManager.AsyncCueSheetManager.GetAtomCueSheet
// 0x0008 (0x0008 - 0x0000)
struct AsyncCueSheetManager_GetAtomCueSheet final
{
public:
	class USoundAtomCueSheet*                     ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(AsyncCueSheetManager_GetAtomCueSheet) == 0x000008, "Wrong alignment on AsyncCueSheetManager_GetAtomCueSheet");
static_assert(sizeof(AsyncCueSheetManager_GetAtomCueSheet) == 0x000008, "Wrong size on AsyncCueSheetManager_GetAtomCueSheet");
static_assert(offsetof(AsyncCueSheetManager_GetAtomCueSheet, ReturnValue) == 0x000000, "Member 'AsyncCueSheetManager_GetAtomCueSheet::ReturnValue' has a wrong offset!");

// Function SoundManager.AsyncCueSheetManager.LoadAsync
// 0x0018 (0x0018 - 0x0000)
struct AsyncCueSheetManager_LoadAsync final
{
public:
	struct FSoftObjectPath                        PathForCueSheet;                                   // 0x0000(0x0018)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(AsyncCueSheetManager_LoadAsync) == 0x000008, "Wrong alignment on AsyncCueSheetManager_LoadAsync");
static_assert(sizeof(AsyncCueSheetManager_LoadAsync) == 0x000018, "Wrong size on AsyncCueSheetManager_LoadAsync");
static_assert(offsetof(AsyncCueSheetManager_LoadAsync, PathForCueSheet) == 0x000000, "Member 'AsyncCueSheetManager_LoadAsync::PathForCueSheet' has a wrong offset!");

// Function SoundManager.LiveLipSync.attachSoundManager
// 0x000C (0x000C - 0x0000)
struct LiveLipSync_attachSoundManager final
{
public:
	int32                                         majNum;                                            // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         minNum;                                            // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(LiveLipSync_attachSoundManager) == 0x000004, "Wrong alignment on LiveLipSync_attachSoundManager");
static_assert(sizeof(LiveLipSync_attachSoundManager) == 0x00000C, "Wrong size on LiveLipSync_attachSoundManager");
static_assert(offsetof(LiveLipSync_attachSoundManager, majNum) == 0x000000, "Member 'LiveLipSync_attachSoundManager::majNum' has a wrong offset!");
static_assert(offsetof(LiveLipSync_attachSoundManager, minNum) == 0x000004, "Member 'LiveLipSync_attachSoundManager::minNum' has a wrong offset!");
static_assert(offsetof(LiveLipSync_attachSoundManager, ReturnValue) == 0x000008, "Member 'LiveLipSync_attachSoundManager::ReturnValue' has a wrong offset!");

// Function SoundManager.LiveLipSync.detachSoundManager
// 0x000C (0x000C - 0x0000)
struct LiveLipSync_detachSoundManager final
{
public:
	int32                                         majNum;                                            // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         minNum;                                            // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(LiveLipSync_detachSoundManager) == 0x000004, "Wrong alignment on LiveLipSync_detachSoundManager");
static_assert(sizeof(LiveLipSync_detachSoundManager) == 0x00000C, "Wrong size on LiveLipSync_detachSoundManager");
static_assert(offsetof(LiveLipSync_detachSoundManager, majNum) == 0x000000, "Member 'LiveLipSync_detachSoundManager::majNum' has a wrong offset!");
static_assert(offsetof(LiveLipSync_detachSoundManager, minNum) == 0x000004, "Member 'LiveLipSync_detachSoundManager::minNum' has a wrong offset!");
static_assert(offsetof(LiveLipSync_detachSoundManager, ReturnValue) == 0x000008, "Member 'LiveLipSync_detachSoundManager::ReturnValue' has a wrong offset!");

// Function SoundManager.LiveLipSync.getLipsyncLiveInfo
// 0x0010 (0x0010 - 0x0000)
struct LiveLipSync_getLipsyncLiveInfo final
{
public:
	struct FCriLipsMouthInfo                      ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(LiveLipSync_getLipsyncLiveInfo) == 0x000004, "Wrong alignment on LiveLipSync_getLipsyncLiveInfo");
static_assert(sizeof(LiveLipSync_getLipsyncLiveInfo) == 0x000010, "Wrong size on LiveLipSync_getLipsyncLiveInfo");
static_assert(offsetof(LiveLipSync_getLipsyncLiveInfo, ReturnValue) == 0x000000, "Member 'LiveLipSync_getLipsyncLiveInfo::ReturnValue' has a wrong offset!");

// Function SoundManager.LiveLipSync.getLipsyncLiveJapanese
// 0x0014 (0x0014 - 0x0000)
struct LiveLipSync_getLipsyncLiveJapanese final
{
public:
	struct FCriLipsMorphTargetBlendAmountAsJapanese ReturnValue;                                     // 0x0000(0x0014)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(LiveLipSync_getLipsyncLiveJapanese) == 0x000004, "Wrong alignment on LiveLipSync_getLipsyncLiveJapanese");
static_assert(sizeof(LiveLipSync_getLipsyncLiveJapanese) == 0x000014, "Wrong size on LiveLipSync_getLipsyncLiveJapanese");
static_assert(offsetof(LiveLipSync_getLipsyncLiveJapanese, ReturnValue) == 0x000000, "Member 'LiveLipSync_getLipsyncLiveJapanese::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.getNumCuePlayingCountByName
// 0x0018 (0x0018 - 0x0000)
struct PlayAdxControl_getNumCuePlayingCountByName final
{
public:
	class FString                                 Name_0;                                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PlayAdxControl_getNumCuePlayingCountByName) == 0x000008, "Wrong alignment on PlayAdxControl_getNumCuePlayingCountByName");
static_assert(sizeof(PlayAdxControl_getNumCuePlayingCountByName) == 0x000018, "Wrong size on PlayAdxControl_getNumCuePlayingCountByName");
static_assert(offsetof(PlayAdxControl_getNumCuePlayingCountByName, Name_0) == 0x000000, "Member 'PlayAdxControl_getNumCuePlayingCountByName::Name_0' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_getNumCuePlayingCountByName, ReturnValue) == 0x000010, "Member 'PlayAdxControl_getNumCuePlayingCountByName::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.attachLipsyncLive
// 0x000C (0x000C - 0x0000)
struct PlayAdxControl_attachLipsyncLive final
{
public:
	int32                                         majorNum;                                          // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         minorNum;                                          // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PlayAdxControl_attachLipsyncLive) == 0x000004, "Wrong alignment on PlayAdxControl_attachLipsyncLive");
static_assert(sizeof(PlayAdxControl_attachLipsyncLive) == 0x00000C, "Wrong size on PlayAdxControl_attachLipsyncLive");
static_assert(offsetof(PlayAdxControl_attachLipsyncLive, majorNum) == 0x000000, "Member 'PlayAdxControl_attachLipsyncLive::majorNum' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_attachLipsyncLive, minorNum) == 0x000004, "Member 'PlayAdxControl_attachLipsyncLive::minorNum' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_attachLipsyncLive, ReturnValue) == 0x000008, "Member 'PlayAdxControl_attachLipsyncLive::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.checkPauseSound
// 0x000C (0x000C - 0x0000)
struct PlayAdxControl_checkPauseSound final
{
public:
	int32                                         PlayerMajorID;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PlayerMinorID;                                     // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PlayAdxControl_checkPauseSound) == 0x000004, "Wrong alignment on PlayAdxControl_checkPauseSound");
static_assert(sizeof(PlayAdxControl_checkPauseSound) == 0x00000C, "Wrong size on PlayAdxControl_checkPauseSound");
static_assert(offsetof(PlayAdxControl_checkPauseSound, PlayerMajorID) == 0x000000, "Member 'PlayAdxControl_checkPauseSound::PlayerMajorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_checkPauseSound, PlayerMinorID) == 0x000004, "Member 'PlayAdxControl_checkPauseSound::PlayerMinorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_checkPauseSound, ReturnValue) == 0x000008, "Member 'PlayAdxControl_checkPauseSound::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.checkPlaying
// 0x000C (0x000C - 0x0000)
struct PlayAdxControl_checkPlaying final
{
public:
	int32                                         PlayerMajorID;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PlayerMinorID;                                     // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PlayAdxControl_checkPlaying) == 0x000004, "Wrong alignment on PlayAdxControl_checkPlaying");
static_assert(sizeof(PlayAdxControl_checkPlaying) == 0x00000C, "Wrong size on PlayAdxControl_checkPlaying");
static_assert(offsetof(PlayAdxControl_checkPlaying, PlayerMajorID) == 0x000000, "Member 'PlayAdxControl_checkPlaying::PlayerMajorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_checkPlaying, PlayerMinorID) == 0x000004, "Member 'PlayAdxControl_checkPlaying::PlayerMinorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_checkPlaying, ReturnValue) == 0x000008, "Member 'PlayAdxControl_checkPlaying::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.checkReadAcb
// 0x0018 (0x0018 - 0x0000)
struct PlayAdxControl_checkReadAcb final
{
public:
	class FString                                 Filename;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PlayAdxControl_checkReadAcb) == 0x000008, "Wrong alignment on PlayAdxControl_checkReadAcb");
static_assert(sizeof(PlayAdxControl_checkReadAcb) == 0x000018, "Wrong size on PlayAdxControl_checkReadAcb");
static_assert(offsetof(PlayAdxControl_checkReadAcb, Filename) == 0x000000, "Member 'PlayAdxControl_checkReadAcb::Filename' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_checkReadAcb, ReturnValue) == 0x000010, "Member 'PlayAdxControl_checkReadAcb::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.checkReadEnd
// 0x0008 (0x0008 - 0x0000)
struct PlayAdxControl_checkReadEnd final
{
public:
	int32                                         bankID;                                            // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0004(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PlayAdxControl_checkReadEnd) == 0x000004, "Wrong alignment on PlayAdxControl_checkReadEnd");
static_assert(sizeof(PlayAdxControl_checkReadEnd) == 0x000008, "Wrong size on PlayAdxControl_checkReadEnd");
static_assert(offsetof(PlayAdxControl_checkReadEnd, bankID) == 0x000000, "Member 'PlayAdxControl_checkReadEnd::bankID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_checkReadEnd, ReturnValue) == 0x000004, "Member 'PlayAdxControl_checkReadEnd::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.createPlayerBank
// 0x0010 (0x0010 - 0x0000)
struct PlayAdxControl_createPlayerBank final
{
public:
	int32                                         PlayerMajorID;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PlayerMinorID;                                     // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          isMulti;                                           // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ReturnValue;                                       // 0x000C(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayAdxControl_createPlayerBank) == 0x000004, "Wrong alignment on PlayAdxControl_createPlayerBank");
static_assert(sizeof(PlayAdxControl_createPlayerBank) == 0x000010, "Wrong size on PlayAdxControl_createPlayerBank");
static_assert(offsetof(PlayAdxControl_createPlayerBank, PlayerMajorID) == 0x000000, "Member 'PlayAdxControl_createPlayerBank::PlayerMajorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_createPlayerBank, PlayerMinorID) == 0x000004, "Member 'PlayAdxControl_createPlayerBank::PlayerMinorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_createPlayerBank, isMulti) == 0x000008, "Member 'PlayAdxControl_createPlayerBank::isMulti' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_createPlayerBank, ReturnValue) == 0x00000C, "Member 'PlayAdxControl_createPlayerBank::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.detachLipsyncLive
// 0x000C (0x000C - 0x0000)
struct PlayAdxControl_detachLipsyncLive final
{
public:
	int32                                         majorNum;                                          // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         minorNum;                                          // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PlayAdxControl_detachLipsyncLive) == 0x000004, "Wrong alignment on PlayAdxControl_detachLipsyncLive");
static_assert(sizeof(PlayAdxControl_detachLipsyncLive) == 0x00000C, "Wrong size on PlayAdxControl_detachLipsyncLive");
static_assert(offsetof(PlayAdxControl_detachLipsyncLive, majorNum) == 0x000000, "Member 'PlayAdxControl_detachLipsyncLive::majorNum' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_detachLipsyncLive, minorNum) == 0x000004, "Member 'PlayAdxControl_detachLipsyncLive::minorNum' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_detachLipsyncLive, ReturnValue) == 0x000008, "Member 'PlayAdxControl_detachLipsyncLive::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.fadeInBGMCategorySoundmanager
// 0x000C (0x000C - 0x0000)
struct PlayAdxControl_fadeInBGMCategorySoundmanager final
{
public:
	int32                                         fadeInTime;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         fadeInVolume;                                      // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PlayAdxControl_fadeInBGMCategorySoundmanager) == 0x000004, "Wrong alignment on PlayAdxControl_fadeInBGMCategorySoundmanager");
static_assert(sizeof(PlayAdxControl_fadeInBGMCategorySoundmanager) == 0x00000C, "Wrong size on PlayAdxControl_fadeInBGMCategorySoundmanager");
static_assert(offsetof(PlayAdxControl_fadeInBGMCategorySoundmanager, fadeInTime) == 0x000000, "Member 'PlayAdxControl_fadeInBGMCategorySoundmanager::fadeInTime' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_fadeInBGMCategorySoundmanager, fadeInVolume) == 0x000004, "Member 'PlayAdxControl_fadeInBGMCategorySoundmanager::fadeInVolume' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_fadeInBGMCategorySoundmanager, ReturnValue) == 0x000008, "Member 'PlayAdxControl_fadeInBGMCategorySoundmanager::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.fadeInSndMng
// 0x000C (0x000C - 0x0000)
struct PlayAdxControl_fadeInSndMng final
{
public:
	int32                                         PlayerMajorID;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PlayerMinorID;                                     // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         fadeInTime;                                        // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayAdxControl_fadeInSndMng) == 0x000004, "Wrong alignment on PlayAdxControl_fadeInSndMng");
static_assert(sizeof(PlayAdxControl_fadeInSndMng) == 0x00000C, "Wrong size on PlayAdxControl_fadeInSndMng");
static_assert(offsetof(PlayAdxControl_fadeInSndMng, PlayerMajorID) == 0x000000, "Member 'PlayAdxControl_fadeInSndMng::PlayerMajorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_fadeInSndMng, PlayerMinorID) == 0x000004, "Member 'PlayAdxControl_fadeInSndMng::PlayerMinorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_fadeInSndMng, fadeInTime) == 0x000008, "Member 'PlayAdxControl_fadeInSndMng::fadeInTime' has a wrong offset!");

// Function SoundManager.PlayAdxControl.fadeOutBGMCategorySoundManager
// 0x000C (0x000C - 0x0000)
struct PlayAdxControl_fadeOutBGMCategorySoundManager final
{
public:
	int32                                         fadeOutTime;                                       // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         fadeOutVolume;                                     // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PlayAdxControl_fadeOutBGMCategorySoundManager) == 0x000004, "Wrong alignment on PlayAdxControl_fadeOutBGMCategorySoundManager");
static_assert(sizeof(PlayAdxControl_fadeOutBGMCategorySoundManager) == 0x00000C, "Wrong size on PlayAdxControl_fadeOutBGMCategorySoundManager");
static_assert(offsetof(PlayAdxControl_fadeOutBGMCategorySoundManager, fadeOutTime) == 0x000000, "Member 'PlayAdxControl_fadeOutBGMCategorySoundManager::fadeOutTime' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_fadeOutBGMCategorySoundManager, fadeOutVolume) == 0x000004, "Member 'PlayAdxControl_fadeOutBGMCategorySoundManager::fadeOutVolume' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_fadeOutBGMCategorySoundManager, ReturnValue) == 0x000008, "Member 'PlayAdxControl_fadeOutBGMCategorySoundManager::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.fadeOutSndMng
// 0x000C (0x000C - 0x0000)
struct PlayAdxControl_fadeOutSndMng final
{
public:
	int32                                         PlayerMajorID;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PlayerMinorID;                                     // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         fadeOutTime;                                       // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayAdxControl_fadeOutSndMng) == 0x000004, "Wrong alignment on PlayAdxControl_fadeOutSndMng");
static_assert(sizeof(PlayAdxControl_fadeOutSndMng) == 0x00000C, "Wrong size on PlayAdxControl_fadeOutSndMng");
static_assert(offsetof(PlayAdxControl_fadeOutSndMng, PlayerMajorID) == 0x000000, "Member 'PlayAdxControl_fadeOutSndMng::PlayerMajorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_fadeOutSndMng, PlayerMinorID) == 0x000004, "Member 'PlayAdxControl_fadeOutSndMng::PlayerMinorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_fadeOutSndMng, fadeOutTime) == 0x000008, "Member 'PlayAdxControl_fadeOutSndMng::fadeOutTime' has a wrong offset!");

// Function SoundManager.PlayAdxControl.getIntegratedLoudness
// 0x0004 (0x0004 - 0x0000)
struct PlayAdxControl_getIntegratedLoudness final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayAdxControl_getIntegratedLoudness) == 0x000004, "Wrong alignment on PlayAdxControl_getIntegratedLoudness");
static_assert(sizeof(PlayAdxControl_getIntegratedLoudness) == 0x000004, "Wrong size on PlayAdxControl_getIntegratedLoudness");
static_assert(offsetof(PlayAdxControl_getIntegratedLoudness, ReturnValue) == 0x000000, "Member 'PlayAdxControl_getIntegratedLoudness::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.getLengthPlayerBank
// 0x0018 (0x0018 - 0x0000)
struct PlayAdxControl_getLengthPlayerBank final
{
public:
	int32                                         majorNum;                                          // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         minorNum;                                          // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CueId;                                             // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	int64                                         ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayAdxControl_getLengthPlayerBank) == 0x000008, "Wrong alignment on PlayAdxControl_getLengthPlayerBank");
static_assert(sizeof(PlayAdxControl_getLengthPlayerBank) == 0x000018, "Wrong size on PlayAdxControl_getLengthPlayerBank");
static_assert(offsetof(PlayAdxControl_getLengthPlayerBank, majorNum) == 0x000000, "Member 'PlayAdxControl_getLengthPlayerBank::majorNum' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_getLengthPlayerBank, minorNum) == 0x000004, "Member 'PlayAdxControl_getLengthPlayerBank::minorNum' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_getLengthPlayerBank, CueId) == 0x000008, "Member 'PlayAdxControl_getLengthPlayerBank::CueId' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_getLengthPlayerBank, ReturnValue) == 0x000010, "Member 'PlayAdxControl_getLengthPlayerBank::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.getLengthSoundBank
// 0x0010 (0x0010 - 0x0000)
struct PlayAdxControl_getLengthSoundBank final
{
public:
	int32                                         bankID;                                            // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CueId;                                             // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayAdxControl_getLengthSoundBank) == 0x000008, "Wrong alignment on PlayAdxControl_getLengthSoundBank");
static_assert(sizeof(PlayAdxControl_getLengthSoundBank) == 0x000010, "Wrong size on PlayAdxControl_getLengthSoundBank");
static_assert(offsetof(PlayAdxControl_getLengthSoundBank, bankID) == 0x000000, "Member 'PlayAdxControl_getLengthSoundBank::bankID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_getLengthSoundBank, CueId) == 0x000004, "Member 'PlayAdxControl_getLengthSoundBank::CueId' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_getLengthSoundBank, ReturnValue) == 0x000008, "Member 'PlayAdxControl_getLengthSoundBank::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.getLipsyncLiveInfo
// 0x0018 (0x0018 - 0x0000)
struct PlayAdxControl_getLipsyncLiveInfo final
{
public:
	int32                                         majorNum;                                          // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         minorNum;                                          // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FCriLipsMouthInfo                      ReturnValue;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayAdxControl_getLipsyncLiveInfo) == 0x000004, "Wrong alignment on PlayAdxControl_getLipsyncLiveInfo");
static_assert(sizeof(PlayAdxControl_getLipsyncLiveInfo) == 0x000018, "Wrong size on PlayAdxControl_getLipsyncLiveInfo");
static_assert(offsetof(PlayAdxControl_getLipsyncLiveInfo, majorNum) == 0x000000, "Member 'PlayAdxControl_getLipsyncLiveInfo::majorNum' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_getLipsyncLiveInfo, minorNum) == 0x000004, "Member 'PlayAdxControl_getLipsyncLiveInfo::minorNum' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_getLipsyncLiveInfo, ReturnValue) == 0x000008, "Member 'PlayAdxControl_getLipsyncLiveInfo::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.getLipsyncLiveJapanese
// 0x001C (0x001C - 0x0000)
struct PlayAdxControl_getLipsyncLiveJapanese final
{
public:
	int32                                         majorNum;                                          // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         minorNum;                                          // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FCriLipsMorphTargetBlendAmountAsJapanese ReturnValue;                                     // 0x0008(0x0014)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayAdxControl_getLipsyncLiveJapanese) == 0x000004, "Wrong alignment on PlayAdxControl_getLipsyncLiveJapanese");
static_assert(sizeof(PlayAdxControl_getLipsyncLiveJapanese) == 0x00001C, "Wrong size on PlayAdxControl_getLipsyncLiveJapanese");
static_assert(offsetof(PlayAdxControl_getLipsyncLiveJapanese, majorNum) == 0x000000, "Member 'PlayAdxControl_getLipsyncLiveJapanese::majorNum' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_getLipsyncLiveJapanese, minorNum) == 0x000004, "Member 'PlayAdxControl_getLipsyncLiveJapanese::minorNum' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_getLipsyncLiveJapanese, ReturnValue) == 0x000008, "Member 'PlayAdxControl_getLipsyncLiveJapanese::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.getMomentaryLoudness
// 0x0004 (0x0004 - 0x0000)
struct PlayAdxControl_getMomentaryLoudness final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayAdxControl_getMomentaryLoudness) == 0x000004, "Wrong alignment on PlayAdxControl_getMomentaryLoudness");
static_assert(sizeof(PlayAdxControl_getMomentaryLoudness) == 0x000004, "Wrong size on PlayAdxControl_getMomentaryLoudness");
static_assert(offsetof(PlayAdxControl_getMomentaryLoudness, ReturnValue) == 0x000000, "Member 'PlayAdxControl_getMomentaryLoudness::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.getShortLoudness
// 0x0004 (0x0004 - 0x0000)
struct PlayAdxControl_getShortLoudness final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayAdxControl_getShortLoudness) == 0x000004, "Wrong alignment on PlayAdxControl_getShortLoudness");
static_assert(sizeof(PlayAdxControl_getShortLoudness) == 0x000004, "Wrong size on PlayAdxControl_getShortLoudness");
static_assert(offsetof(PlayAdxControl_getShortLoudness, ReturnValue) == 0x000000, "Member 'PlayAdxControl_getShortLoudness::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.GetTime
// 0x000C (0x000C - 0x0000)
struct PlayAdxControl_GetTime final
{
public:
	int32                                         PlayerMajorID;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PlayerMinorID;                                     // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ReturnValue;                                       // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayAdxControl_GetTime) == 0x000004, "Wrong alignment on PlayAdxControl_GetTime");
static_assert(sizeof(PlayAdxControl_GetTime) == 0x00000C, "Wrong size on PlayAdxControl_GetTime");
static_assert(offsetof(PlayAdxControl_GetTime, PlayerMajorID) == 0x000000, "Member 'PlayAdxControl_GetTime::PlayerMajorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_GetTime, PlayerMinorID) == 0x000004, "Member 'PlayAdxControl_GetTime::PlayerMinorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_GetTime, ReturnValue) == 0x000008, "Member 'PlayAdxControl_GetTime::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.IsLoop
// 0x000C (0x000C - 0x0000)
struct PlayAdxControl_IsLoop final
{
public:
	int32                                         PlayerMajorID;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PlayerMinorID;                                     // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PlayAdxControl_IsLoop) == 0x000004, "Wrong alignment on PlayAdxControl_IsLoop");
static_assert(sizeof(PlayAdxControl_IsLoop) == 0x00000C, "Wrong size on PlayAdxControl_IsLoop");
static_assert(offsetof(PlayAdxControl_IsLoop, PlayerMajorID) == 0x000000, "Member 'PlayAdxControl_IsLoop::PlayerMajorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_IsLoop, PlayerMinorID) == 0x000004, "Member 'PlayAdxControl_IsLoop::PlayerMinorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_IsLoop, ReturnValue) == 0x000008, "Member 'PlayAdxControl_IsLoop::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.pauseSound
// 0x000C (0x000C - 0x0000)
struct PlayAdxControl_pauseSound final
{
public:
	int32                                         PlayerMajorID;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PlayerMinorID;                                     // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          flag;                                              // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PlayAdxControl_pauseSound) == 0x000004, "Wrong alignment on PlayAdxControl_pauseSound");
static_assert(sizeof(PlayAdxControl_pauseSound) == 0x00000C, "Wrong size on PlayAdxControl_pauseSound");
static_assert(offsetof(PlayAdxControl_pauseSound, PlayerMajorID) == 0x000000, "Member 'PlayAdxControl_pauseSound::PlayerMajorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_pauseSound, PlayerMinorID) == 0x000004, "Member 'PlayAdxControl_pauseSound::PlayerMinorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_pauseSound, flag) == 0x000008, "Member 'PlayAdxControl_pauseSound::flag' has a wrong offset!");

// Function SoundManager.PlayAdxControl.releasePlayerBank
// 0x0008 (0x0008 - 0x0000)
struct PlayAdxControl_releasePlayerBank final
{
public:
	int32                                         PlayerMajorID;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PlayerMinorID;                                     // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayAdxControl_releasePlayerBank) == 0x000004, "Wrong alignment on PlayAdxControl_releasePlayerBank");
static_assert(sizeof(PlayAdxControl_releasePlayerBank) == 0x000008, "Wrong size on PlayAdxControl_releasePlayerBank");
static_assert(offsetof(PlayAdxControl_releasePlayerBank, PlayerMajorID) == 0x000000, "Member 'PlayAdxControl_releasePlayerBank::PlayerMajorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_releasePlayerBank, PlayerMinorID) == 0x000004, "Member 'PlayAdxControl_releasePlayerBank::PlayerMinorID' has a wrong offset!");

// Function SoundManager.PlayAdxControl.requestFreeAcb
// 0x0004 (0x0004 - 0x0000)
struct PlayAdxControl_requestFreeAcb final
{
public:
	int32                                         bankID;                                            // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayAdxControl_requestFreeAcb) == 0x000004, "Wrong alignment on PlayAdxControl_requestFreeAcb");
static_assert(sizeof(PlayAdxControl_requestFreeAcb) == 0x000004, "Wrong size on PlayAdxControl_requestFreeAcb");
static_assert(offsetof(PlayAdxControl_requestFreeAcb, bankID) == 0x000000, "Member 'PlayAdxControl_requestFreeAcb::bankID' has a wrong offset!");

// Function SoundManager.PlayAdxControl.requestLoadAcb
// 0x0018 (0x0018 - 0x0000)
struct PlayAdxControl_requestLoadAcb final
{
public:
	class FString                                 Filename;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PlayAdxControl_requestLoadAcb) == 0x000008, "Wrong alignment on PlayAdxControl_requestLoadAcb");
static_assert(sizeof(PlayAdxControl_requestLoadAcb) == 0x000018, "Wrong size on PlayAdxControl_requestLoadAcb");
static_assert(offsetof(PlayAdxControl_requestLoadAcb, Filename) == 0x000000, "Member 'PlayAdxControl_requestLoadAcb::Filename' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_requestLoadAcb, ReturnValue) == 0x000010, "Member 'PlayAdxControl_requestLoadAcb::ReturnValue' has a wrong offset!");

// Function SoundManager.PlayAdxControl.requestSound
// 0x0010 (0x0010 - 0x0000)
struct PlayAdxControl_requestSound final
{
public:
	int32                                         PlayerMajorID;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PlayerMinorID;                                     // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CueId;                                             // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          isForceChange;                                     // 0x000C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PlayAdxControl_requestSound) == 0x000004, "Wrong alignment on PlayAdxControl_requestSound");
static_assert(sizeof(PlayAdxControl_requestSound) == 0x000010, "Wrong size on PlayAdxControl_requestSound");
static_assert(offsetof(PlayAdxControl_requestSound, PlayerMajorID) == 0x000000, "Member 'PlayAdxControl_requestSound::PlayerMajorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_requestSound, PlayerMinorID) == 0x000004, "Member 'PlayAdxControl_requestSound::PlayerMinorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_requestSound, CueId) == 0x000008, "Member 'PlayAdxControl_requestSound::CueId' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_requestSound, isForceChange) == 0x00000C, "Member 'PlayAdxControl_requestSound::isForceChange' has a wrong offset!");

// Function SoundManager.PlayAdxControl.setPlayerAcbBank
// 0x0010 (0x0010 - 0x0000)
struct PlayAdxControl_setPlayerAcbBank final
{
public:
	int32                                         PlayerMajorID;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PlayerMinorID;                                     // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPlayerType                                   Type;                                              // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         bankID;                                            // 0x000C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayAdxControl_setPlayerAcbBank) == 0x000004, "Wrong alignment on PlayAdxControl_setPlayerAcbBank");
static_assert(sizeof(PlayAdxControl_setPlayerAcbBank) == 0x000010, "Wrong size on PlayAdxControl_setPlayerAcbBank");
static_assert(offsetof(PlayAdxControl_setPlayerAcbBank, PlayerMajorID) == 0x000000, "Member 'PlayAdxControl_setPlayerAcbBank::PlayerMajorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_setPlayerAcbBank, PlayerMinorID) == 0x000004, "Member 'PlayAdxControl_setPlayerAcbBank::PlayerMinorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_setPlayerAcbBank, Type) == 0x000008, "Member 'PlayAdxControl_setPlayerAcbBank::Type' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_setPlayerAcbBank, bankID) == 0x00000C, "Member 'PlayAdxControl_setPlayerAcbBank::bankID' has a wrong offset!");

// Function SoundManager.PlayAdxControl.stopSound
// 0x0008 (0x0008 - 0x0000)
struct PlayAdxControl_stopSound final
{
public:
	int32                                         PlayerMajorID;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PlayerMinorID;                                     // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayAdxControl_stopSound) == 0x000004, "Wrong alignment on PlayAdxControl_stopSound");
static_assert(sizeof(PlayAdxControl_stopSound) == 0x000008, "Wrong size on PlayAdxControl_stopSound");
static_assert(offsetof(PlayAdxControl_stopSound, PlayerMajorID) == 0x000000, "Member 'PlayAdxControl_stopSound::PlayerMajorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_stopSound, PlayerMinorID) == 0x000004, "Member 'PlayAdxControl_stopSound::PlayerMinorID' has a wrong offset!");

// Function SoundManager.PlayAdxControl.stopSound_IMD
// 0x0008 (0x0008 - 0x0000)
struct PlayAdxControl_stopSound_IMD final
{
public:
	int32                                         PlayerMajorID;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PlayerMinorID;                                     // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayAdxControl_stopSound_IMD) == 0x000004, "Wrong alignment on PlayAdxControl_stopSound_IMD");
static_assert(sizeof(PlayAdxControl_stopSound_IMD) == 0x000008, "Wrong size on PlayAdxControl_stopSound_IMD");
static_assert(offsetof(PlayAdxControl_stopSound_IMD, PlayerMajorID) == 0x000000, "Member 'PlayAdxControl_stopSound_IMD::PlayerMajorID' has a wrong offset!");
static_assert(offsetof(PlayAdxControl_stopSound_IMD, PlayerMinorID) == 0x000004, "Member 'PlayAdxControl_stopSound_IMD::PlayerMinorID' has a wrong offset!");

// Function SoundManager.SoundManagerReadyAsyncFunction.SoundManagerReadyAsyncFunction
// 0x0020 (0x0020 - 0x0000)
struct SoundManagerReadyAsyncFunction_SoundManagerReadyAsyncFunction final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UPlayAdxControl*                        Control;                                           // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         bankID;                                            // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundManagerReadyAsyncFunction*        ReturnValue;                                       // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(SoundManagerReadyAsyncFunction_SoundManagerReadyAsyncFunction) == 0x000008, "Wrong alignment on SoundManagerReadyAsyncFunction_SoundManagerReadyAsyncFunction");
static_assert(sizeof(SoundManagerReadyAsyncFunction_SoundManagerReadyAsyncFunction) == 0x000020, "Wrong size on SoundManagerReadyAsyncFunction_SoundManagerReadyAsyncFunction");
static_assert(offsetof(SoundManagerReadyAsyncFunction_SoundManagerReadyAsyncFunction, WorldContextObject) == 0x000000, "Member 'SoundManagerReadyAsyncFunction_SoundManagerReadyAsyncFunction::WorldContextObject' has a wrong offset!");
static_assert(offsetof(SoundManagerReadyAsyncFunction_SoundManagerReadyAsyncFunction, Control) == 0x000008, "Member 'SoundManagerReadyAsyncFunction_SoundManagerReadyAsyncFunction::Control' has a wrong offset!");
static_assert(offsetof(SoundManagerReadyAsyncFunction_SoundManagerReadyAsyncFunction, bankID) == 0x000010, "Member 'SoundManagerReadyAsyncFunction_SoundManagerReadyAsyncFunction::bankID' has a wrong offset!");
static_assert(offsetof(SoundManagerReadyAsyncFunction_SoundManagerReadyAsyncFunction, ReturnValue) == 0x000018, "Member 'SoundManagerReadyAsyncFunction_SoundManagerReadyAsyncFunction::ReturnValue' has a wrong offset!");

// Function SoundManager.SoundManagerGameInstanceSubSystem.GetPlayAdxControl
// 0x0008 (0x0008 - 0x0000)
struct SoundManagerGameInstanceSubSystem_GetPlayAdxControl final
{
public:
	class UPlayAdxControl*                        ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(SoundManagerGameInstanceSubSystem_GetPlayAdxControl) == 0x000008, "Wrong alignment on SoundManagerGameInstanceSubSystem_GetPlayAdxControl");
static_assert(sizeof(SoundManagerGameInstanceSubSystem_GetPlayAdxControl) == 0x000008, "Wrong size on SoundManagerGameInstanceSubSystem_GetPlayAdxControl");
static_assert(offsetof(SoundManagerGameInstanceSubSystem_GetPlayAdxControl, ReturnValue) == 0x000000, "Member 'SoundManagerGameInstanceSubSystem_GetPlayAdxControl::ReturnValue' has a wrong offset!");

}

