#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TmxAssetPlugin

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class TmxAssetPlugin.TmxAsset
// 0x0018 (0x0040 - 0x0028)
class UTmxAsset final : public UObject
{
public:
	class UTexture*                               mpTex;                                             // 0x0028(0x0008)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<int8>                                  mBuf;                                              // 0x0030(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TmxAsset">();
	}
	static class UTmxAsset* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTmxAsset>();
	}
};
static_assert(alignof(UTmxAsset) == 0x000008, "Wrong alignment on UTmxAsset");
static_assert(sizeof(UTmxAsset) == 0x000040, "Wrong size on UTmxAsset");
static_assert(offsetof(UTmxAsset, mpTex) == 0x000028, "Member 'UTmxAsset::mpTex' has a wrong offset!");
static_assert(offsetof(UTmxAsset, mBuf) == 0x000030, "Member 'UTmxAsset::mBuf' has a wrong offset!");

}

